language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npx parcel build src/index.html --public-url=.
env:
  - NODE_ENV=production
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN
on:
  branch: master
